enableTelemetry: false

nodeLinker: pnp

npmPublishAccess: "restricted"

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: ${GH_REGISTRY_TOKEN}

yarnPath: .yarn/releases/yarn-3.2.3.cjs
