name: Snapshot

on:
  workflow_dispatch:

concurrency:
  group: snapshot-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  snapshot:
    name: Snapshot
    if: github.repository_owner == 'wojteek' && github.ref_name == 'snapshot'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - name: Create
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "ci: ${{ github.ref_name }} snapshot"
          title: "ci: ${{ github.ref_name }} snapshot"
          createGithubReleases: false
          publish: yarn workspaces foreach --no-private npm publish --tolerate-republish --tag ${{ github.ref_name }}
          version: yarn changeset version --snapshot ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
