name: Snapshot

on:
  workflow_dispatch:

concurrency:
  group: snapshot-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  snapshot:
    name: Snapshot
    if: github.repository_owner == 'wojteek' && github.ref_name == 'snapshot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - name: Check if pre-release mode
        run: |
          readonly pre_file="${{ github.workspace }}/.changeset/pre.json"
          
          function is_prerelease_mode() {
            [[ "$(jq '.mode' -r $pre_file)" == "pre" ]] && return 0 || return 1
          }

          is_prerelease_mode
          readonly pre_status=$?
          [[ $pre_status -eq 1 ]] && echo "make a release"
          [[ $pre_status -eq 0 ]] && echo "run changeset pre exit"
          exit 0
        shell: bash
      - name: Create
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "ci: ${{ github.ref_name }} release"
          title: "ci: ${{ github.ref_name }} release"
          createGithubReleases: false
          publish: yarn workspaces foreach --no-private npm publish --tolerate-republish --tag ${{ github.ref_name }}
          version: yarn changeset version --snapshot ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
