name: Snapshot

on:
  workflow_dispatch:

concurrency:
  group: snapshot-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  snapshot:
    name: Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - run: yarn changeset status --verbose
      - name: Create
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "ci: ${{ github.ref_name }} snapshot"
          title: "ci: ${{ github.ref_name }} snapshot"
          createGithubReleases: false
          publish: yarn changeset publish --no-git-tag --tag ${{ github.ref_name }}
          version: yarn changeset version --snapshot ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
