name: Release

on:
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - name: Create PR
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "ci: ${{ github.ref_name }} release"
          title: "ci: ${{ github.ref_name }} release"
          createGithubReleases: true
          publish: yarn workspaces foreach --no-private npm publish --tolerate-republish
          version: yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tags
        id: tags
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const { runTagCommand } = await import('${{ github.workspace }}/scripts/changesets.mjs');
            
            let releasedPackages = [];
            try {
              releasedPackages = await runTagCommand({ cwd: process.cwd(), exec });
            } catch(err) {
              core.warning(`changeset tag error: ${err}`);
            }
            
            core.setOutput('releasedPackages', JSON.stringify(releasedPackages));
            core.setOutput('hasReleasedPackages', !!releasedPackages.length);
        env:
          NODE_OPTIONS: --require="./.pnp.cjs" --experimental-loader="./.pnp.loader.mjs"
      - name: Create releases
        if: steps.tags.outputs.hasReleasedPackages == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { createRelease } = await import('${{ github.workspace }}/scripts/release.mjs');
            await Promise.all(${{ steps.tags.outputs.releasedPackages }}.map((pkg) => createRelease({ octokit: github, pkg, context })));
        env:
          NODE_OPTIONS: --require="./.pnp.cjs" --experimental-loader="./.pnp.loader.mjs"
      - name: Push tags
        if: steps.tags.outputs.hasReleasedPackages == 'true'
        run: |
          git push --follow-tags
