name: Snapshot publish

on:
  workflow_run:
    workflows: [ Snapshot ]
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: yarn install --immutable
      - name: Create
        id: changesets
        uses: changesets/action@v1
        if: success()
        with:
          commit: "ci: ${{ github.ref_name }} release"
          title: "ci: ${{ github.ref_name }} release"
          createGithubReleases: false
          publish: yarn workspaces foreach --no-private npm publish --tolerate-republish --tag ${{ github.ref_name }}
          version: yarn changeset version --snapshot ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
